# Generated by Django 6.0.6 on 2026-06-11 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queryauditlog',
            options={'ordering': ['-created_at'], 'verbose_name': '질의 감사 로그', 'verbose_name_plural': '질의 감사 로그 목록'},
        ),
    ]
