# Generated by Django 6.0.6 on 2026-06-11 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_queryauditlog_options'),
        ('characters', '0003_alter_aicharacter_contact_policy_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryauditlog',
            name='answer_preview',
            field=models.TextField(blank=True, verbose_name='답변 요약'),
        ),
        migrations.AlterField(
            model_name='queryauditlog',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.aicharacter', verbose_name='대상 AI 캐릭터'),
        ),
        migrations.AlterField(
            model_name='queryauditlog',
            name='citation_summary',
            field=models.TextField(blank=True, verbose_name='참조 문서 요약'),
        ),
        migrations.AlterField(
            model_name='queryauditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='queryauditlog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='오류 메시지'),
        ),
        migrations.AlterField(
            model_name='queryauditlog',
            name='question',
            field=models.TextField(verbose_name='질의 내용'),
        ),
        migrations.AlterField(
            model_name='queryauditlog',
            name='status',
            field=models.CharField(max_length=40, verbose_name='처리 상태'),
        ),
        migrations.AlterField(
            model_name='queryauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='질의자'),
        ),
    ]
