# Generated by Django 6.0.6 on 2026-06-11 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationunit',
            options={'ordering': ['name'], 'verbose_name': '부서/조직', 'verbose_name_plural': '부서/조직 목록'},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['organization__name', 'display_name'], 'verbose_name': '임직원(데모)', 'verbose_name_plural': '임직원 목록'},
        ),
    ]
