# Generated by Django 6.0.6 on 2026-06-11 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_alter_organizationunit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='kind',
            field=models.CharField(choices=[('institution', '기관'), ('headquarters', '본부'), ('office', '실'), ('team', '팀')], max_length=24, verbose_name='조직 유형'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='name',
            field=models.CharField(max_length=120, verbose_name='조직/부서명'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='orgs.organizationunit', verbose_name='상위 조직'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='display_name',
            field=models.CharField(max_length=80, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='duty_keywords',
            field=models.TextField(blank=True, verbose_name='담당 업무'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='extension',
            field=models.CharField(blank=True, max_length=40, verbose_name='내선 번호'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='is_demo',
            field=models.BooleanField(default=True, verbose_name='데모 계정 여부'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='orgs.organizationunit', verbose_name='소속 조직'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(blank=True, max_length=80, verbose_name='직급/직책'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
    ]
