# Generated by Django 6.0.6 on 2026-06-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_alter_organizationunit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationunit',
            options={'verbose_name': '부서/조직', 'verbose_name_plural': '부서/조직 목록'},
        ),
        migrations.RemoveConstraint(
            model_name='organizationunit',
            name='unique_org_unit_under_parent',
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='path',
            field=models.CharField(default='0001', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='organizationunit',
            name='parent',
        ),
    ]
