# Generated by Django 6.0.6 on 2026-06-11 03:43

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('source_file', models.FileField(upload_to='raw/%Y/%m/', validators=[documents.models.validate_supported_document])),
                ('parsed_markdown', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('uploaded', '업로드'), ('parsed', '파싱완료'), ('failed', '파싱실패'), ('inactive', '비활성')], default='uploaded', max_length=20)),
                ('is_latest', models.BooleanField(default=True)),
                ('parse_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='characters.aicharacter')),
            ],
            options={
                'ordering': ['title', '-created_at'],
            },
        ),
    ]
