# Generated by Django 6.0.6 on 2026-06-11 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulationdocument',
            options={'ordering': ['title', '-created_at'], 'verbose_name': '규정 문서', 'verbose_name_plural': '규정 문서 목록'},
        ),
    ]
