# Generated by Django 6.0.6 on 2026-06-11 05:03

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_aicharacter_contact_policy_note_and_more'),
        ('documents', '0002_alter_regulationdocument_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulationdocument',
            options={'ordering': ['title', '-created_at']},
        ),
        migrations.AlterField(
            model_name='regulationdocument',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='characters.aicharacter', verbose_name='연결된 AI 캐릭터'),
        ),
        migrations.AlterField(
            model_name='regulationdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='regulationdocument',
            name='is_latest',
            field=models.BooleanField(default=True, verbose_name='최신 본 여부'),
        ),
        migrations.AlterField(
            model_name='regulationdocument',
            name='parse_error',
            field=models.TextField(blank=True, verbose_name='파싱 오류 메시지'),
        ),
        migrations.AlterField(
            model_name='regulationdocument',
            name='parsed_markdown',
            field=models.TextField(blank=True, verbose_name='파싱된 마크다운'),
        ),
        migrations.AlterField(
            model_name='regulationdocument',
            name='revision_date',
            field=models.DateField(blank=True, null=True, verbose_name='개정 일자'),
        ),
        migrations.AlterField(
            model_name='regulationdocument',
            name='source_file',
            field=models.FileField(upload_to='raw/%Y/%m/', validators=[documents.models.validate_supported_document], verbose_name='원본 파일 (HWP/PDF)'),
        ),
        migrations.AlterField(
            model_name='regulationdocument',
            name='status',
            field=models.CharField(choices=[('uploaded', '업로드'), ('parsed', '파싱완료'), ('failed', '파싱실패'), ('inactive', '비활성')], default='uploaded', max_length=20, verbose_name='처리 상태'),
        ),
        migrations.AlterField(
            model_name='regulationdocument',
            name='title',
            field=models.CharField(max_length=200, verbose_name='문서 제목'),
        ),
        migrations.AlterField(
            model_name='regulationdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
    ]
