# Generated by Django 6.0.6 on 2026-06-11 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClauseIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=40)),
                ('paragraph', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('keywords', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='documents.regulationdocument')),
            ],
            options={
                'ordering': ['document__title', 'article', 'paragraph'],
                'constraints': [models.UniqueConstraint(fields=('document', 'article', 'paragraph', 'body'), name='unique_clause_text_per_document')],
            },
        ),
    ]
