# Generated by Django 6.0.6 on 2026-06-11 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clauseindex',
            options={'ordering': ['document__title', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='clauseindex',
            name='unique_clause_text_per_document',
        ),
    ]
