# Generated by Django 6.0.6 on 2026-06-11 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0002_alter_clauseindex_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clauseindex',
            options={'ordering': ['document', 'id'], 'verbose_name': '조항 인덱스', 'verbose_name_plural': '조항 인덱스 목록'},
        ),
    ]
