# Generated by Django 6.0.6 on 2026-06-11 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_regulationdocument_options_and_more'),
        ('indexing', '0003_alter_clauseindex_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clauseindex',
            options={'ordering': ['document__title', 'id'], 'verbose_name': '조항 인덱스', 'verbose_name_plural': '조항 인덱스 목록'},
        ),
        migrations.AlterField(
            model_name='clauseindex',
            name='article',
            field=models.CharField(max_length=40, verbose_name='조 (Article)'),
        ),
        migrations.AlterField(
            model_name='clauseindex',
            name='body',
            field=models.TextField(verbose_name='조항 본문'),
        ),
        migrations.AlterField(
            model_name='clauseindex',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='clauseindex',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='documents.regulationdocument', verbose_name='소속 규정 문서'),
        ),
        migrations.AlterField(
            model_name='clauseindex',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='clauseindex',
            name='keywords',
            field=models.TextField(blank=True, verbose_name='추출된 키워드'),
        ),
        migrations.AlterField(
            model_name='clauseindex',
            name='paragraph',
            field=models.CharField(blank=True, max_length=40, verbose_name='항/호 (Paragraph)'),
        ),
        migrations.AlterField(
            model_name='clauseindex',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='조항 제목'),
        ),
    ]
