# Generated by Django 6.0.6 on 2026-06-11 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Gemini'), ('openai', 'OpenAI'), ('claude', 'Claude')], max_length=20)),
                ('display_name', models.CharField(max_length=120)),
                ('encrypted_api_key', models.TextField()),
                ('key_last4', models.CharField(blank=True, max_length=4)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_secret_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'display_name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'display_name'), name='unique_secret_provider_display_name')],
            },
        ),
    ]
