# Generated by Django 6.0.6 on 2026-06-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretcredential',
            options={'ordering': ['provider', 'display_name'], 'verbose_name': '보안 인증 키', 'verbose_name_plural': '보안 인증 키 목록'},
        ),
        migrations.AlterField(
            model_name='secretcredential',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('openai', 'OpenAI'), ('claude', 'Claude'), ('openrouter', 'OpenRouter')], max_length=20),
        ),
    ]
