# Generated by Django 6.0.6 on 2026-06-11 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretstore', '0002_alter_secretcredential_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretcredential',
            options={'ordering': ['provider', 'display_name'], 'verbose_name': '보안 키 관리', 'verbose_name_plural': '보안 키 목록'},
        ),
        migrations.AlterField(
            model_name='secretcredential',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='secretcredential',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_secret_credentials', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AlterField(
            model_name='secretcredential',
            name='display_name',
            field=models.CharField(max_length=120, verbose_name='표시 이름'),
        ),
        migrations.AlterField(
            model_name='secretcredential',
            name='encrypted_api_key',
            field=models.TextField(verbose_name='암호화된 API 키'),
        ),
        migrations.AlterField(
            model_name='secretcredential',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='secretcredential',
            name='key_last4',
            field=models.CharField(blank=True, max_length=4, verbose_name='키 마지막 4자리'),
        ),
        migrations.AlterField(
            model_name='secretcredential',
            name='last_tested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 테스트 일시'),
        ),
        migrations.AlterField(
            model_name='secretcredential',
            name='model_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='사용 모델명'),
        ),
        migrations.AlterField(
            model_name='secretcredential',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('openai', 'OpenAI'), ('claude', 'Claude'), ('openrouter', 'OpenRouter')], max_length=20, verbose_name='API 제공자'),
        ),
        migrations.AlterField(
            model_name='secretcredential',
            name='rotated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='키 교체 일시'),
        ),
        migrations.AlterField(
            model_name='secretcredential',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
    ]
