# Generated by Django 6.0.6 on 2026-06-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretstore', '0003_alter_secretcredential_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretcredential',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('openai', 'OpenAI'), ('claude', 'Claude'), ('openrouter', 'OpenRouter'), ('local', 'Local LLM')], max_length=20, verbose_name='API 제공자'),
        ),
    ]
