# Generated by Django 6.0.6 on 2026-06-11 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicharacter',
            options={'ordering': ['name'], 'verbose_name': 'AI 캐릭터', 'verbose_name_plural': 'AI 캐릭터 목록'},
        ),
    ]
