# Generated by Django 6.0.6 on 2026-06-11 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_aicharacter_options'),
        ('orgs', '0003_alter_organizationunit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicharacter',
            name='contact_policy_note',
            field=models.TextField(blank=True, verbose_name='담당자 안내 문구'),
        ),
        migrations.AlterField(
            model_name='aicharacter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='aicharacter',
            name='description',
            field=models.TextField(blank=True, verbose_name='캐릭터 설명'),
        ),
        migrations.AlterField(
            model_name='aicharacter',
            name='duty_keywords',
            field=models.TextField(blank=True, verbose_name='업무 키워드'),
        ),
        migrations.AlterField(
            model_name='aicharacter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='사용 여부'),
        ),
        migrations.AlterField(
            model_name='aicharacter',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='캐릭터명'),
        ),
        migrations.AlterField(
            model_name='aicharacter',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_characters', to='orgs.organizationunit', verbose_name='소속 부서(조직)'),
        ),
        migrations.AlterField(
            model_name='aicharacter',
            name='persona_prompt',
            field=models.TextField(blank=True, verbose_name='페르소나 프롬프트'),
        ),
        migrations.AlterField(
            model_name='aicharacter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
    ]
