# Generated by Django 6.0.6 on 2026-06-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_aicharacter_contact_policy_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicharacter',
            name='is_unrestricted',
            field=models.BooleanField(default=False, verbose_name='자유 대화 모드(규정 제한 없음)'),
        ),
    ]
